name: Deploy Docs

on:
  push:
    branches: [ master ] 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install JSDoc (if not globally installed)
        run: npm install -g jsdoc

      - name: Generate Documentation
        run: jsdoc -c jsdoc.config.json

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./docs  

      - name: Deploy to GitHub Pages (optional)
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          publish_dir: ./docs
          force_orphan: true
